# -*- coding: utf-8 -*-
import xlrd
import os

def change_special(str):
    str2 = ''
    try:
        for character in str:
            if character == '®':
                R = """&#174;"""
                str2 = str2 + R
            elif character == '<':
                left = """&lt;"""
                str2 = str2 + left
            elif character == '<':
                right = """&gt;"""
                str2 = str2 + right
            else:
                str2 = str2 + character
    except:
        pass
    return str2
def makestr(list_a,A,B,C,D,E,F,G,H,I,J,b,l):
    tag = list_a[1]
    No = int(list_a[0])


    li = [A,B,C,D,E,F,G,H,I,J]
    for x in range(len(li)):
        if len(li[x]) == 0:
            X = x
            break
    li = li[0:X]
    print(li)

    if No <10:
        No = "00{0}".format(No)

    elif No >9 and No <100:
        No = "0{0}".format(No)

    str1 = """
<!-- Table Generated by Methods.py Author: OHAD -->
<h2 id = "{0}">{0}</h2>
""".format(tag)
    for i in range(len(A)):
        if A[i] == 'p':
            str2 = """<p>{0}</p>""".format(B[i])
            str1 = str1 + str2

        elif A[i] == 'l':
            str31 ='''<ol>'''
            if A[i - 1] != 'l' or i == 0:
                str1 = str1+ str31
            str32 ='''</ol>'''
            A2=A[i:len(A)]
            str4 = """<li>{0}</li>""".format(B[i])
            str1 = str1 +str4


            if A[i+1] != 'l':
                str1 = str1 + str32
            if A[i - 1] != 't' or i == 0:
                str1 = str1+ """< table >< tr >"""
                for y in range(1,len(li)):
                    str5 = """ < th > {0} < / th > """.format(li[y][0])
                    str1 = str1 + str5
                str1 = str1 + """ < / tr > """



            elif A[i-1] == 't' and A[i+1] == 't':
                for t in range(i,b-1):
                    for z in range(1,X):
                        str5 = """ < td > {0} < / td > """.format((li[z][t]))
                        s1 = s1 + str5
                    s1 = s1 + s2
                    str1 = str1 + s1
                    s1 = str4
            elif A[i+1] != t:
                for y in range(i,len(li)):
                    str6 = """ < td > {0} < / td > """.format(li[y][i])
                    str1 = str1 + str6
                str5 = """
                </table>
                <!-- Table end -->
                """
                str1 = str1 + str5

        elif A[i] == 'end':
            break




    return str1

book = xlrd.open_workbook('Excel/Methods.xlsx')
sentense = """"""
list_tag = []
list_No = []
#どこのシートまで記入されているかを判定
for i in range(book.nsheets): #i = sheet_numbers
    sheet = book.sheet_by_index(i)
    if sheet.ncols == 4 and sheet.nrows ==2:
        num = i
        break

#excel fileから値を取得
for l in range(num):
    sheet = book.sheet_by_index(l)
    list_a = []


    for row in range(0, 2):  # 0~5指定だということに注意　つまりセルの1~6
        list_a.append(sheet.cell(row, 1).value)


    list_A = []
    list_B = []
    list_C = []
    list_D = []
    list_E = []
    list_F = []
    list_G = []
    list_H = []
    list_I = []
    list_J = []

    for row in range(2, sheet.nrows):
        try:
            list_A.append(sheet.cell(row,0).value)
            list_B.append(sheet.cell(row,1).value)
            list_C.append(sheet.cell(row,2).value)
            list_D.append(sheet.cell(row,3).value)
            list_E.append(sheet.cell(row, 4).value)
            list_F.append(sheet.cell(row, 5).value)
            list_G.append(sheet.cell(row, 6).value)
            list_H.append(sheet.cell(row, 7).value)
            list_I.append(sheet.cell(row, 8).value)
            list_J.append(sheet.cell(row, 9).value)
        except:
            pass


    for b in range(0,len(list_B)):
        if list_A[b] == '':
            list_A[b]=list_A[b-1]

        elif list_A[b] == 'end':
            list_A[b] == 'end'
            break
    try:
        for a in range(b):
            if list_B[a] =='':
                list_B[a] = list_B[a-1]

        for c in range(b):
            if list_C[c] == '':
                list_C[c]=list_C[c-1]

        for d in range(b):
            if list_D[d] == '':
                list_D[d]=list_D[d-1]

        for e in range(b):
            if list_E[e] == '':
                list_E[e] = list_E[e - 1]

        for f in range(b):
            if list_F[f] == '':
                list_F[f] = list_F[f - 1]

        for g in range(b):
            if list_G[g] == '':
                list_G[g] = list_G[g - 1]

        for h in range(b):
            if list_H[h] == '':
                list_H[h] = list_H[h - 1]

        for ii in range(b):
            if list_I[ii] == '':
                list_I[ii] = list_I[ii - 1]

        for j in range(b):
            if list_J[j] == '':
                list_J[j] = list_J[j - 1]
    except:
        pass

    try:
        list_A = list_A[0:b+1]
        list_B = list_B[0:b]
        list_C = list_C[0:b]
        list_D = list_D[0:b]
        list_E = list_E[0:b]
        list_F = list_F[0:b]
        list_G = list_G[0:b]
        list_H = list_H[0:b]
        list_I = list_I[0:b]
        list_J = list_J[0:b]
    except:
        pass


   #txt fileへの出力
    str = makestr(list_a,list_A,list_B,list_C,list_D,list_E,list_F,list_G,list_H,list_I,list_J,b,l)
    sentense = sentense + str




f = open('Block/Block_Methodmaker.txt', 'w')
f.write(sentense)
f.close()

for l1 in range(num):
    sheet = book.sheet_by_index(l1)
    list_c= []


    for row in range(0, 2):  # 0~5指定だということに注意　つまりセルの1~6
        list_c.append(sheet.cell(row, 1).value)
    list_tag.append(list_c[1])
    list_No.append(int(list_c[0]))


# make Block_Contents_materials.txt
m1 =""
for i in range(len(list_tag)):
    m2 = """
<li><a href="#{0}">4-{1} {0}</a></li>""".format(list_tag[i],list_No[i])
    m1 = m1 + m2

f = open('Block/Block_Contents_methods.txt', 'w')
f.write(m1)
f.close()